trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: pwd
  displayName: 'Print Work Directory'
- script: echo "Hello123" > test.txt
  displayName: 'Create Test File'
- script: cat /home/vsts/work/1/s/test.txt 
  displayName: 'Show File Contents'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
